spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Client_DR
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.security: DEBUG  # Enable DEBUG level logging for security-related information


